### ISSUE TITLE
In Puzzle Variety, goal counters of three digits show corrupted graphics

### ISSUE THREAD

**Issue by TheOpponent** [DerekPascarella/SakuraWarsColumns2-EnglishPatchDreamcast#2]
For example, this puzzle in DLC 3 has the objective of clearing 120 gems. The first two digits show as a black square until the counter goes under 100.
![Screenshot 2021-05-04 00-07-08](https://user-images.githubusercontent.com/8432212/117476880-56399180-af2b-11eb-8620-0207e64384d5.png)

This is running on USA Dreamcast using MODE.

**Comment by DerekPascarella** [comment]
I was able to reproduce this issue:

![image](https://user-images.githubusercontent.com/28241702/117481070-73bd2a00-af30-11eb-91b3-30e1b6fd8a90.png)

However, this bug is also present in the original unpatched Japanese version:

![image](https://user-images.githubusercontent.com/28241702/117481200-a49d5f00-af30-11eb-89ab-f9209767a01b.png)

**Comment by DerekPascarella** [comment]
Being that the DLC is a very minor part of the game and this is not a game-breaking bug AND is present in the original version, I have opted not to address it.

Thank you so much for pointing it out, though.  I appreciate it!

**NOTE:** This does not seem to affect any of the "normal" in-game puzzle challenges, but only some of the DLC puzzles.
